<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login_admin extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_admin');
    }

    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			redirect('index.php/member');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('Login_admin');
		}
		else
		{
			$ceklogin=$this->Model_admin->ceklogin(
			$this->input->post('username'),
			$this->input->post('password')
				);
			if(!empty($ceklogin)) {
				$this->session->set_userdata('username',$ceklogin->username);
				$this->session->set_userdata('logined',true);
				redirect('index.php/Member');
			}
				
			else 
			{
				redirect("Login_admin");
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		$this->session->unset_userdata('username');
		redirect('index.php/Login_admin');
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */