   <?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_member');
    }

    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			redirect('Home');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('Login');
		}
		else
		{
			
			$cekuser=$this->Model_member->cekuser(
			$this->input->post('username'),
			$this->input->post('password')
				);
			if(!empty($cekuser)) {
				$this->session->set_userdata('username',$cekuser->username);
				$this->session->set_userdata('nama',$cekuser->nama);
				$this->session->set_userdata('alamat',$cekuser->alamat);

				$this->session->set_userdata('logined',true);
				redirect('index.php/Home');
			}
			else 
			{
				redirect("/");
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		$this->session->unset_userdata('username');
		redirect('index.php/Login');
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */